export const currentPosition = {
  id: "4CATornto",
  level: "4",
  title: "Sales Rep",
  region: "Toronto",
  managers: ["1VP", "2NA", "3CA"],
  status: "normal",
};

export const hierarchy = [
  {
    id: "1VP",
    level: "1",
    title: "VP of Sales",
    status: "critical",
    inCharge: ["North America", "Europe"],
    lowerLevel: [
      {
        id: "2NA",
        level: "2",
        title: "Sales Manager",
        region: "North America",
        managers: ["1VP"],
        inCharge: ["Canada", "USA"],
        status: "critical",
        lowerLevel: [
          {
            id: "3CA",
            level: "3",
            title: "Sales Lead",
            region: "Canada",
            managers: ["1VP", "2NA"],
            inCharge: ["Toronto", "Vancouver"],
            status: "normal",
            lowerLevel: [
              {
                id: "4CATornto",
                level: "4",
                title: "Sales Rep",
                region: "Toronto",
                managers: ["1VP", "2NA", "3CA"],
                status: "normal",
              },
              {
                id: "4CAVancouver",
                level: "4",
                title: "Sales Rep",
                region: "Vancouver",
                managers: ["1VP", "2NA", "3CA"],
                status: "normal",
              },
            ],
          },
          {
            id: "3US",
            level: "3",
            title: "Sales Lead",
            region: "USA",
            managers: ["1VP", "2NA"],
            inCharge: ["New York", "Dallas", "Los Angeles"],
            status: "critical",
            lowerLevel: [
              {
                id: "4USNewYork",
                level: "4",
                title: "Sales Rep",
                region: "New York",
                managers: ["1VP", "2NA", "3US"],
                status: "warning",
              },
              {
                id: "4USDallas",
                level: "4",
                title: "Sales Rep",
                region: "Dallas",
                managers: ["1VP", "2NA", "3US"],
                status: "critical",
              },
              {
                id: "4USLosAngeles",
                level: "4",
                title: "Sales Rep",
                region: "Los Angeles",
                managers: ["1VP", "2NA", "3US"],
                status: "critical",
              },
            ],
          },
        ],
      },
      {
        id: "2EUR",
        level: "2",
        title: "Sales Manager",
        region: "Europe",
        managers: ["1VP"],
        inCharge: ["Germany", "Italy"],
        status: "warning",
        lowerLevel: [
          {
            id: "3GER",
            level: "3",
            title: "Sales Lead",
            region: "Germany",
            managers: ["1VP", "2EUR"],
            inCharge: ["Berlin", "Frankfurt"],
            status: "warning",
            lowerLevel: [
              {
                id: "4GERBerlin",
                level: "4",
                title: "Sales Rep",
                region: "Berlin",
                managers: ["1VP", "2EUR", "3GER"],
                status: "normal",
              },
              {
                id: "4GERFrankfurt",
                level: "4",
                title: "Sales Rep",
                region: "Frankfurt",
                managers: ["1VP", "2EUR", "3GER"],
                status: "critical",
              },
            ],
          },
          {
            id: "3IT",
            level: "3",
            title: "Sales Lead",
            region: "Italy",
            managers: ["1VP", "2EUR"],
            inCharge: ["Milan"],
            status: "normal",
            lowerLevel: [
              {
                id: "4ITMilan",
                level: "4",
                title: "Sales Rep",
                region: "Milan",
                managers: ["1VP", "2EUR", "3IT"],
                status: "normal",
              },
            ],
          },
        ],
      },
    ],
  },
];

export const heavyHierarchy = [
  {
    id: "1VP",
    level: "1",
    title: "VP of Sales",
    status: "critical",
    inCharge: ["North America", "South America", "Asia", "Europe"],
    lowerLevel: [
      {
        id: "2NA",
        level: "2",
        title: "Sales Manager",
        region: "North America",
        managers: ["1VP"],
        inCharge: ["Canada", "USA"],
        status: "critical",
        lowerLevel: [
          {
            id: "3CA",
            level: "3",
            title: "Sales Lead",
            region: "Canada",
            managers: ["1VP", "2NA"],
            inCharge: ["Toronto"],
            status: "normal",
            lowerLevel: [
              {
                id: "4CATornto",
                level: "4",
                title: "Sales Rep",
                region: "Toronto",
                managers: ["1VP", "2NA", "3CA"],
                status: "normal",
              },
            ],
          },
          {
            id: "3US",
            level: "3",
            title: "Sales Lead",
            region: "USA",
            managers: ["1VP", "2NA"],
            inCharge: ["New York"],
            status: "critical",
            lowerLevel: [
              {
                id: "4USNewYork",
                level: "4",
                title: "Sales Rep",
                region: "New York",
                managers: ["1VP", "2NA", "3US"],
                status: "warning",
              },
            ],
          },
        ],
      },
      {
        id: "2SA",
        level: "2",
        title: "Sales Manager",
        region: "South America",
        managers: ["1VP"],
        inCharge: ["Brazil", "Colombia", "Mexico", "Argentina"],
        status: "normal",
        lowerLevel: [
          {
            id: "3BR",
            level: "3",
            title: "Sales Lead",
            region: "Brazil",
            managers: ["1VP", "2SA"],
            inCharge: ["Brasilia"],
            status: "normal",
            lowerLevel: [
              {
                id: "4BRBrasilia",
                level: "4",
                title: "Sales Rep",
                region: "Brasilia",
                managers: ["1VP", "2SA", "3BR"],
                status: "normal",
              },
            ],
          },
          {
            id: "3COL",
            level: "3",
            title: "Sales Lead",
            region: "Colombia",
            managers: ["1VP", "2SA"],
            inCharge: ["Bogotá"],
            status: "warning",
            lowerLevel: [
              {
                id: "4COLBogotá",
                level: "4",
                title: "Sales Rep",
                region: "Bogotá",
                managers: ["1VP", "2SA", "3COL"],
                status: "warning",
              },
            ],
          },
          {
            id: "3MX",
            level: "3",
            title: "Sales Lead",
            region: "Mexico",
            managers: ["1VP", "2SA"],
            inCharge: ["MexicoCity"],
            status: "warning",
            lowerLevel: [
              {
                id: "4MXMexicoCity",
                level: "4",
                title: "Sales Rep",
                region: "Mexico City",
                managers: ["1VP", "2SA", "3MX"],
                status: "warning",
              },
            ],
          },
          {
            id: "3ARG",
            level: "3",
            title: "Sales Lead",
            region: "Argentina",
            managers: ["1VP", "2SA"],
            inCharge: ["BuenosAires"],
            status: "normal",
            lowerLevel: [
              {
                id: "4ARGBuenosAires",
                level: "4",
                title: "Sales Rep",
                region: "Buenos Aires",
                managers: ["1VP", "2SA", "3ARG"],
                status: "normal",
              },
            ],
          },
        ],
      },
      {
        id: "2AS",
        level: "2",
        title: "Sales Manager",
        region: "Asia",
        managers: ["1VP"],
        inCharge: ["Korea", "China", "Japan", "Singapore"],
        status: "critical",
        lowerLevel: [
          {
            id: "3KR",
            level: "3",
            title: "Sales Lead",
            region: "Korea",
            managers: ["1VP", "2AS"],
            inCharge: ["Seoul"],
            status: "warning",
            lowerLevel: [
              {
                id: "4KRSeoul",
                level: "4",
                title: "Sales Rep",
                region: "Seoul",
                managers: ["1VP", "2AS", "3KR"],
                status: "warning",
              },
            ],
          },
          {
            id: "3CN",
            level: "3",
            title: "Sales Lead",
            region: "China",
            managers: ["1VP", "2AS"],
            inCharge: ["Beijing"],
            status: "warning",
            lowerLevel: [
              {
                id: "4CNBeijing",
                level: "4",
                title: "Sales Rep",
                region: "Beijing",
                managers: ["1VP", "2AS", "3CN"],
                status: "warning",
              },
            ],
          },
          {
            id: "3JP",
            level: "3",
            title: "Sales Lead",
            region: "Japan",
            managers: ["1VP", "2AS"],
            inCharge: ["Tokyo"],
            status: "critical",
            lowerLevel: [
              {
                id: "4JPTokyo",
                level: "4",
                title: "Sales Rep",
                region: "Tokyo",
                managers: ["1VP", "2AS", "3JP"],
                status: "critical",
              },
            ],
          },
          {
            id: "3SG",
            level: "3",
            title: "Sales Lead",
            region: "Singapore",
            managers: ["1VP", "2AS"],
            inCharge: ["Singapore"],
            status: "critical",
            lowerLevel: [
              {
                id: "4ARGBuenosAires",
                level: "4",
                title: "Sales Rep",
                region: "Singapore",
                managers: ["1VP", "2AS", "3SG"],
                status: "critical",
              },
            ],
          },
        ],
      },
      {
        id: "2EUR",
        level: "2",
        title: "Sales Manager",
        region: "Europe",
        managers: ["1VP"],
        inCharge: ["Germany", "Italy", "France", "Spain"],
        status: "warning",
        lowerLevel: [
          {
            id: "3GER",
            level: "3",
            title: "Sales Lead",
            region: "Germany",
            managers: ["1VP", "2EUR"],
            inCharge: ["Berlin"],
            status: "warning",
            lowerLevel: [
              {
                id: "4GERBerlin",
                level: "4",
                title: "Sales Rep",
                region: "Berlin",
                managers: ["1VP", "2EUR", "3GER"],
                status: "warning",
              },
            ],
          },
          {
            id: "3FR",
            level: "3",
            title: "Sales Lead",
            region: "France",
            managers: ["1VP", "2EUR"],
            inCharge: ["Paris"],
            status: "warning",
            lowerLevel: [
              {
                id: "4FRParis",
                level: "4",
                title: "Sales Rep",
                region: "Paris",
                managers: ["1VP", "2EUR", "3FR"],
                status: "warning",
              },
            ],
          },
          {
            id: "3IT",
            level: "3",
            title: "Sales Lead",
            region: "Italy",
            managers: ["1VP", "2EUR"],
            inCharge: ["Milan"],
            status: "normal",
            lowerLevel: [
              {
                id: "4ITMilan",
                level: "4",
                title: "Sales Rep",
                region: "Milan",
                managers: ["1VP", "2EUR", "3IT"],
                status: "normal",
              },
            ],
          },
          {
            id: "3ES",
            level: "3",
            title: "Sales Lead",
            region: "Spain",
            managers: ["1VP", "2EUR"],
            inCharge: ["Madrid"],
            status: "warning",
            lowerLevel: [
              {
                id: "4ESMadrid",
                level: "4",
                title: "Sales Rep",
                region: "Madrid",
                managers: ["1VP", "2EUR", "3ES"],
                status: "warning",
              },
            ],
          },
        ],
      },
    ],
  },
];

export const leanHierarchy = [
  {
    id: "1VP",
    level: "1",
    title: "VP of Sales",
    status: "critical",
    inCharge: ["North America", "Europe"],
    lowerLevel: [
      {
        id: "2NA",
        level: "2",
        title: "Sales Manager",
        region: "North America",
        managers: ["1VP"],
        inCharge: ["Canada", "USA"],
        status: "critical",
        lowerLevel: [
          {
            id: "3CA",
            level: "3",
            title: "Sales Lead",
            region: "Canada",
            managers: ["1VP", "2NA"],
            inCharge: ["Waterloo", "Toronto", "Vancouver", "Calgary", "Quebec"],
            status: "critical",
            lowerLevel: [
              {
                id: "4CATornto",
                level: "4",
                title: "Sales Rep",
                region: "Toronto",
                managers: ["1VP", "2NA", "3CA"],
                status: "normal",
              },
              {
                id: "4CAVancouver",
                level: "4",
                title: "Sales Rep",
                region: "Vancouver",
                managers: ["1VP", "2NA", "3CA"],
                status: "critical",
              },
              {
                id: "4CAWaterloo",
                level: "4",
                title: "Sales Rep",
                region: "Waterloo",
                managers: ["1VP", "2NA", "3CA"],
                status: "warning",
              },
              {
                id: "4CACalgary",
                level: "4",
                title: "Sales Rep",
                region: "Calgary",
                managers: ["1VP", "2NA", "3CA"],
                status: "critical",
              },
              {
                id: "4CAQuebec",
                level: "4",
                title: "Sales Rep",
                region: "Quebec",
                managers: ["1VP", "2NA", "3CA"],
                status: "critical",
              },
            ],
          },
          {
            id: "3US",
            level: "3",
            title: "Sales Lead",
            region: "USA",
            managers: ["1VP", "2NA"],
            inCharge: [
              "New York",
              "Dallas",
              "Los Angeles",
              "Chicago",
              "Boston",
              "Memphis",
            ],
            status: "critical",
            lowerLevel: [
              {
                id: "4USNewYork",
                level: "4",
                title: "Sales Rep",
                region: "New York",
                managers: ["1VP", "2NA", "3US"],
                status: "warning",
              },
              {
                id: "4USDallas",
                level: "4",
                title: "Sales Rep",
                region: "Dallas",
                managers: ["1VP", "2NA", "3US"],
                status: "critical",
              },
              {
                id: "4USLosAngeles",
                level: "4",
                title: "Sales Rep",
                region: "Los Angeles",
                managers: ["1VP", "2NA", "3US"],
                status: "critical",
              },
              {
                id: "4USChicago",
                level: "4",
                title: "Sales Rep",
                region: "Chicago",
                managers: ["1VP", "2NA", "3US"],
                status: "warning",
              },
              {
                id: "4USBoston",
                level: "4",
                title: "Sales Rep",
                region: "Boston",
                managers: ["1VP", "2NA", "3US"],
                status: "warning",
              },
              {
                id: "4USMemphis",
                level: "4",
                title: "Sales Rep",
                region: "Memphis",
                managers: ["1VP", "2NA", "3US"],
                status: "critical",
              },
            ],
          },
        ],
      },
      {
        id: "2EUR",
        level: "2",
        title: "Sales Manager",
        region: "Europe",
        managers: ["1VP"],
        inCharge: ["Germany", "Italy"],
        status: "warning",
        lowerLevel: [
          {
            id: "3GER",
            level: "3",
            title: "Sales Lead",
            region: "Germany",
            managers: ["1VP", "2EUR"],
            inCharge: ["Berlin", "Frankfurt", "Munich", "Hamburg"],
            status: "warning",
            lowerLevel: [
              {
                id: "4GERBerlin",
                level: "4",
                title: "Sales Rep",
                region: "Berlin",
                managers: ["1VP", "2EUR", "3GER"],
                status: "normal",
              },
              {
                id: "4GERFrankfurt",
                level: "4",
                title: "Sales Rep",
                region: "Frankfurt",
                managers: ["1VP", "2EUR", "3GER"],
                status: "critical",
              },
              {
                id: "4GERMunich",
                level: "4",
                title: "Sales Rep",
                region: "Munich",
                managers: ["1VP", "2EUR", "3GER"],
                status: "normal",
              },
              {
                id: "4GERHamburg",
                level: "4",
                title: "Sales Rep",
                region: "Hamburg",
                managers: ["1VP", "2EUR", "3GER"],
                status: "warning",
              },
            ],
          },
          {
            id: "3IT",
            level: "3",
            title: "Sales Lead",
            region: "Italy",
            managers: ["1VP", "2EUR"],
            inCharge: ["Milan", "Rome", "Pisa", "Lecce"],
            status: "normal",
            lowerLevel: [
              {
                id: "4ITMilan",
                level: "4",
                title: "Sales Rep",
                region: "Milan",
                managers: ["1VP", "2EUR", "3IT"],
                status: "normal",
              },
              {
                id: "4ITRome",
                level: "4",
                title: "Sales Rep",
                region: "Rome",
                managers: ["1VP", "2EUR", "3IT"],
                status: "critical",
              },
              {
                id: "4ITPisa",
                level: "4",
                title: "Sales Rep",
                region: "Pisa",
                managers: ["1VP", "2EUR", "3IT"],
                status: "normal",
              },
              {
                id: "4ITLecce",
                level: "4",
                title: "Sales Rep",
                region: "Lecce",
                managers: ["1VP", "2EUR", "3IT"],
                status: "normal",
              },
            ],
          },
        ],
      },
    ],
  },
];
