export const hierarchy = [
  {
    id: "1VP",
    level: "1",
    title: "VP of Sales",
    status: "critical",
    inCharge: ["North America", "Europe"],
    lowerLevel: [
      {
        id: "2NA",
        level: "2",
        title: "Sales Manager",
        region: "North America",
        inCharge: ["Canada", "USA"],
        status: "critical",
        lowerLevel: [
          {
            id: "3CA",
            level: "3",
            title: "Sales Lead",
            region: "Canada",
            inCharge: ["Toronto", "Vancouver"],
            status: "normal",
            lowerLevel: [
              {
                id: "4CATornto",
                level: "4",
                title: "Sales Rep",
                region: "Toronto",
                status: "normal",
              },
              {
                id: "4CAVancouver",
                level: "4",
                title: "Sales Rep",
                region: "Vancouver",
                status: "normal",
              },
            ],
          },
          {
            id: "3US",
            level: "3",
            title: "Sales Lead",
            region: "USA",
            inCharge: ["New York", "Dallas", "Los Angeles"],
            status: "critical",
            lowerLevel: [
              {
                id: "4USNewYork",
                level: "4",
                title: "Sales Rep",
                region: "New York",
                status: "warning",
              },
              {
                id: "4USDallas",
                level: "4",
                title: "Sales Rep",
                region: "Dallas",
                status: "critical",
              },
              {
                id: "4USLosAngeles",
                level: "4",
                title: "Sales Rep",
                region: "Los Angeles",
                status: "critical",
              },
            ],
          },
        ],
      },
      {
        id: "2EUR",
        level: "2",
        title: "Sales Manager",
        region: "Europe",
        inCharge: ["Germany", "Italy"],
        status: "warning",
        lowerLevel: [
          {
            id: "3GER",
            level: "3",
            title: "Sales Lead",
            region: "Germany",
            inCharge: ["Berlin", "Frankfurt"],
            status: "warning",
            lowerLevel: [
              {
                id: "4GERBerlin",
                level: "4",
                title: "Sales Rep",
                region: "Berlin",
                status: "normal",
              },
              {
                id: "4GERFrankfurt",
                level: "4",
                title: "Sales Rep",
                region: "Frankfurt",
                status: "critical",
              },
            ],
          },
          {
            id: "3IT",
            level: "3",
            title: "Sales Lead",
            region: "Italy",
            inCharge: ["Milan"],
            status: "normal",
            lowerLevel: [
              {
                id: "4ITMilan",
                level: "4",
                title: "Sales Rep",
                region: "Milan",
                status: "normal",
              },
            ],
          },
        ],
      },
    ],
  },
];
